require('./db.js')
const express = require('express')
const bodyParser = require('body-parser')
const cors = require('cors')

var user_controller = require('./routes/users_controller')
var group_controller = require('./routes/group_controller')
var research_paper_controller = require('./routes/research_paper_controller')
var marks_controller = require('./routes/marks_controller')
var topic_controller = require('./routes/topic_controller')
var presentation_controller = require('./routes/presentation_controller')
var schedule_controller = require('./routes/schedule_controller')

var app = express()
app.use(bodyParser.json())
app.use(cors({origin:'http://localhost:3000'}))
app.listen(3500,()=>console.log('Server started at : 3500'))

app.use('/user_api',user_controller)
app.use('/group_api',group_controller)
app.use('/topic_api',topic_controller)
app.use('/marks_api',marks_controller)
app.use('/schedule_api',schedule_controller)
app.use('/research_paper_api',research_paper_controller)
app.use('/presentation_api',presentation_controller)
app.use(express.static('public'))